language: python
python:
    - '2.7'
    - '3.5'
install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"

    - conda config --set always_yes yes --set changeps1 no
    - conda create -n travis python=$TRAVIS_PYTHON_VERSION
    - conda env update -n travis -f conda/dev-environment.yml
    - if [ -f conda/dev-environment-py${TRAVIS_PYTHON_VERSION}.yml ]; then conda env update -n travis -f conda/dev-environment-py${TRAVIS_PYTHON_VERSION}.yml; fi
    - source activate travis

    - pip install --upgrade pytest coverage codecov codeclimate-test-reporter
    - pip install .
script:
    - coverage run --source nchash -m py.test
after_success:
    - codecov
    - codeclimate-test-reporter
# deploy:
#   provider: pypi
#   user:
#   password:
#     secure: 
#   on:
#     tags: true
#     repo: aidanheerdegen/nchash
#   distributions: "sdist bdist_wheel"
