version: 2.0
jobs:
    py27:
        working_directory: /circleci
        docker:
            - image: scottwales/conda-build
              environment:
                PYTHON_VER: 2.7

        steps:
            - checkout

            - run: |
                conda build conda --python=${PYTHON_VER}

            - run: |
                mkdir /artefacts
                cp $(conda build conda --python=${PYTHON_VER} --output) /artefacts

            - persist_to_workspace:
                root: /artefacts
                paths: '*'

    py36:
        working_directory: /circleci
        docker:
            - image: scottwales/conda-build
              environment:
                PYTHON_VER: 3.6

        steps:
            - checkout

            - run: |
                conda build conda --python=${PYTHON_VER}

            - run: |
                mkdir /artefacts
                cp $(conda build conda --python=${PYTHON_VER} --output) /artefacts

            - persist_to_workspace:
                root: /artefacts
                paths: '*'

    publish:
        working_directory: /circleci
        docker:
            - image: scottwales/conda-build
        steps:
            - attach_workspace:
                at: /artefacts

            - run:
                anaconda --token "${ANACONDA_TOKEN}" upload --user "${ANACONDA_USER}" /artefacts/*.tar.bz2

workflows:
    version: 2.0
    build_and_publsh:
        jobs:
            - py27:
                filters:
                    tags:
                        only: /.*/

            - py36:
                filters:
                    tags:
                        only: /.*/

            - publish:
                requires:
                    - py27
                    - py36
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
